# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12xsWQpo25DrJ810phxiCKDrN3BtwD7nI
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("dark")

st.header("Proyek Analisis Data: Bike Sharing Dataset")

day_df = pd.read_csv("dashboard/day.csv")
hour_df = pd.read_csv("dashboard/hour.csv")

# Komponen Filter
day_df["dteday"] = pd.to_datetime(day_df["dteday"])
hour_df["dteday"] = pd.to_datetime(hour_df["dteday"])

min_date = day_df["dteday"].min()
max_date = day_df["dteday"].max()

with st.sidebar:
  # Menambahkan logi perusahaan
  st.image("https://github.com/dicodingacademy/assets/raw/main/logo.png")

  # Mengambil start_date dan end_date dari date_input
  start_date, end_date = st.date_input(
      label="Rentang Waktu",
      min_value=min_date,
      max_value=max_date,
      value=[min_date, max_date]
  )

day_df = day_df[(day_df["dteday"] >= pd.to_datetime(start_date)) & (day_df["dteday"] <= pd.to_datetime(end_date))]
hour_df = hour_df[(hour_df["dteday"] >= pd.to_datetime(start_date)) & (hour_df["dteday"] <= pd.to_datetime(end_date))]

## Pertanyaan 1
st.write("***Bagaimana kondisi cuaca memengaruhi jumlah penyewaan sepeda?***")

byweather_df = day_df.groupby(by="weathersit").cnt.sum().sort_values(ascending=False).reset_index()

weather_mapping = {1: "Cerah", 2: "Mendung", 3: "Buruk"}
byweather_df["weathersit"] = byweather_df["weathersit"].replace(weather_mapping)

highest_index = byweather_df["cnt"].idxmax()

color = ["lightgray"] * len(byweather_df)
color[highest_index] = "#578FCA"

plt.figure(figsize=(8, 6))
sns.barplot(x="weathersit", y="cnt", data=byweather_df, palette=color)
plt.title("Jumlah Peminjaman Sepeda Berdasarkan Kondisi Cuaca", loc="center", fontsize=12)
plt.xlabel("Kondisi Cuaca")
plt.ylabel("Jumlah Peminjaman Sepeda")
plt.show()

st.pyplot(plt.gcf())

# Pertanyaan 2
st.write("***Bagaimana musim memengaruhi jumlah penyewaan sepeda?***")

byseason_df = day_df.groupby(by="season").cnt.sum()

season_mapping = {1: "Semi", 2: "Panas", 3: "Gugur", 4: "Dingin"}
byseason_df = byseason_df.reset_index()
byseason_df["season"] = byseason_df["season"].replace(season_mapping)

plt.figure(figsize=(8, 6))
sns.barplot(
    x="season",
    y="cnt",
    data=byseason_df,
    palette=["#578FCA" if s == byseason_df.loc[byseason_df["cnt"].idxmax(), "season"] else "lightgray" for s in byseason_df["season"]],
    order=byseason_df["season"]
)

plt.title("Jumlah Peminjaman Sepeda Berdasarkan Musim", loc="center", fontsize=12)
plt.xlabel("Musim")
plt.ylabel("Jumlah Peminjaman Sepeda")
plt.show()

st.pyplot(plt.gcf())

st.caption("Copyright (c) Jocelyn Nathaniel P")